"""add_platform_recommendation

Revision ID: 60a1b4be027a
Revises: ccf12ac05bae
Create Date: 2026-03-07 06:23:41.036950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a1b4be027a'
down_revision: Union[str, None] = 'ccf12ac05bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_recommendations',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_analysis_hash', sa.String(length=64), nullable=False),
    sa.Column('worst_metric', sa.String(length=30), nullable=False),
    sa.Column('recommended_products', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index('idx_rec_user_hash', 'product_recommendations', ['user_id', 'source_analysis_hash'], unique=False)
    op.add_column('products', sa.Column('platform', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('popularity_rank', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('skin_targets', sa.JSON(), nullable=True))
    op.create_index('idx_products_platform_active', 'products', ['platform', 'is_active'], unique=False)
    op.create_index('idx_products_platform_rank', 'products', ['platform', 'popularity_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_platform_rank', table_name='products')
    op.drop_index('idx_products_platform_active', table_name='products')
    op.drop_column('products', 'skin_targets')
    op.drop_column('products', 'popularity_rank')
    op.drop_column('products', 'platform')
    op.drop_index('idx_rec_user_hash', table_name='product_recommendations')
    op.drop_table('product_recommendations')
    # ### end Alembic commands ###
