"""initial schema - all tables

Revision ID: ccf12ac05bae
Revises: 
Create Date: 2026-03-07 04:53:34.236653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf12ac05bae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('key_ingredients', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='chk_products_price'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('idx_products_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_products_brand_name', 'products', ['brand', 'product_name'], unique=False)
    op.create_index('idx_products_category', 'products', ['category'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('skin_type', sa.String(length=20), nullable=True),
    sa.Column('skin_concerns', sa.JSON(), nullable=True),
    sa.Column('baseline_skin_score', sa.SmallInteger(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female', 'other')", name='chk_users_gender'),
    sa.CheckConstraint("skin_type IN ('dry', 'oily', 'combination', 'sensitive', 'normal')", name='chk_users_skin_type'),
    sa.CheckConstraint('age >= 10 AND age <= 120', name='chk_users_age'),
    sa.CheckConstraint('baseline_skin_score >= 0 AND baseline_skin_score <= 100', name='chk_users_baseline_score'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_skin_type', 'users', ['skin_type'], unique=False)
    op.create_table('product_effect_analyses',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_period_start', sa.Date(), nullable=False),
    sa.Column('analysis_period_end', sa.Date(), nullable=False),
    sa.Column('effect_score', sa.Float(), nullable=False),
    sa.Column('metric_deltas', sa.JSON(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('usage_duration_days', sa.Integer(), nullable=False),
    sa.Column('before_avg_score', sa.Float(), nullable=True),
    sa.Column('after_avg_score', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('analysis_version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('analysis_period_end >= analysis_period_start', name='chk_analysis_period'),
    sa.CheckConstraint('confidence_level >= 0 AND confidence_level <= 1', name='chk_effect_confidence'),
    sa.CheckConstraint('effect_score >= -100 AND effect_score <= 100', name='chk_effect_score'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index('idx_effect_product', 'product_effect_analyses', ['product_id', 'effect_score'], unique=False)
    op.create_index('idx_effect_user_date', 'product_effect_analyses', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_effect_user_product', 'product_effect_analyses', ['user_id', 'product_id'], unique=False)
    op.create_index('idx_effect_user_score', 'product_effect_analyses', ['user_id', 'effect_score'], unique=False)
    op.create_table('product_usage_history',
    sa.Column('usage_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('time_of_day', sa.String(length=10), nullable=True),
    sa.Column('satisfaction_rating', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'occasional')", name='chk_usage_frequency'),
    sa.CheckConstraint("time_of_day IN ('morning', 'night', 'both')", name='chk_usage_time_of_day'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='chk_date_range'),
    sa.CheckConstraint('satisfaction_rating >= 1 AND satisfaction_rating <= 5', name='chk_usage_satisfaction'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('idx_usage_date_range', 'product_usage_history', ['user_id', 'start_date', 'end_date'], unique=False)
    op.create_index('idx_usage_product', 'product_usage_history', ['product_id', 'is_active'], unique=False)
    op.create_index('idx_usage_user_active', 'product_usage_history', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_usage_user_product', 'product_usage_history', ['user_id', 'product_id'], unique=False)
    op.create_table('skin_measurements',
    sa.Column('measurement_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('hydration_score', sa.Float(), nullable=False),
    sa.Column('elasticity_score', sa.Float(), nullable=False),
    sa.Column('pore_score', sa.Float(), nullable=False),
    sa.Column('wrinkle_score', sa.Float(), nullable=False),
    sa.Column('pigmentation_score', sa.Float(), nullable=False),
    sa.Column('overall_skin_score', sa.SmallInteger(), nullable=False),
    sa.Column('classification_data', sa.JSON(), nullable=True),
    sa.Column('regression_data', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('capture_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('elasticity_score >= 0 AND elasticity_score <= 1', name='chk_sm_elasticity'),
    sa.CheckConstraint('hydration_score >= 0 AND hydration_score <= 100', name='chk_sm_hydration'),
    sa.CheckConstraint('overall_skin_score >= 0 AND overall_skin_score <= 100', name='chk_sm_overall'),
    sa.CheckConstraint('pigmentation_score >= 0 AND pigmentation_score <= 350', name='chk_sm_pigmentation'),
    sa.CheckConstraint('pore_score >= 0 AND pore_score <= 2600', name='chk_sm_pore'),
    sa.CheckConstraint('wrinkle_score >= 0 AND wrinkle_score <= 50', name='chk_sm_wrinkle'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    op.create_index('idx_skin_measurements_measured_at', 'skin_measurements', ['measured_at'], unique=False)
    op.create_index('idx_skin_measurements_overall_score', 'skin_measurements', ['user_id', 'overall_skin_score'], unique=False)
    op.create_index('idx_skin_measurements_user_date', 'skin_measurements', ['user_id', 'measured_at'], unique=False)
    op.create_table('skincare_routines',
    sa.Column('routine_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('routine_date', sa.Date(), nullable=False),
    sa.Column('time_of_day', sa.String(length=10), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('total_products', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("time_of_day IN ('morning', 'night')", name='chk_routine_time_of_day'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('routine_id'),
    sa.UniqueConstraint('user_id', 'routine_date', 'time_of_day', name='uq_routine_user_date_time')
    )
    op.create_index('idx_routines_template', 'skincare_routines', ['user_id', 'is_template'], unique=False)
    op.create_index('idx_routines_user_date', 'skincare_routines', ['user_id', 'routine_date'], unique=False)
    op.create_table('daily_skin_scores',
    sa.Column('score_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_id', sa.String(length=36), nullable=True),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('overall_score', sa.SmallInteger(), nullable=False),
    sa.Column('hydration_norm', sa.Float(), nullable=True),
    sa.Column('elasticity_norm', sa.Float(), nullable=True),
    sa.Column('pore_norm', sa.Float(), nullable=True),
    sa.Column('wrinkle_norm', sa.Float(), nullable=True),
    sa.Column('pigmentation_norm', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('trend_velocity', sa.Float(), nullable=True),
    sa.Column('ma_7_score', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("trend_direction IN ('improving', 'stable', 'declining')", name='chk_daily_trend'),
    sa.CheckConstraint('elasticity_norm >= 0 AND elasticity_norm <= 1', name='chk_daily_elasticity'),
    sa.CheckConstraint('hydration_norm >= 0 AND hydration_norm <= 1', name='chk_daily_hydration'),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name='chk_daily_overall'),
    sa.CheckConstraint('pigmentation_norm >= 0 AND pigmentation_norm <= 1', name='chk_daily_pigmentation'),
    sa.CheckConstraint('pore_norm >= 0 AND pore_norm <= 1', name='chk_daily_pore'),
    sa.CheckConstraint('wrinkle_norm >= 0 AND wrinkle_norm <= 1', name='chk_daily_wrinkle'),
    sa.ForeignKeyConstraint(['measurement_id'], ['skin_measurements.measurement_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_id'),
    sa.UniqueConstraint('user_id', 'score_date', name='uq_daily_score_user_date')
    )
    op.create_index('idx_daily_scores_anomaly', 'daily_skin_scores', ['user_id', 'is_anomaly'], unique=False)
    op.create_index('idx_daily_scores_trend', 'daily_skin_scores', ['user_id', 'trend_direction'], unique=False)
    op.create_index('idx_daily_scores_user_date', 'daily_skin_scores', ['user_id', 'score_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_daily_scores_user_date', table_name='daily_skin_scores')
    op.drop_index('idx_daily_scores_trend', table_name='daily_skin_scores')
    op.drop_index('idx_daily_scores_anomaly', table_name='daily_skin_scores')
    op.drop_table('daily_skin_scores')
    op.drop_index('idx_routines_user_date', table_name='skincare_routines')
    op.drop_index('idx_routines_template', table_name='skincare_routines')
    op.drop_table('skincare_routines')
    op.drop_index('idx_skin_measurements_user_date', table_name='skin_measurements')
    op.drop_index('idx_skin_measurements_overall_score', table_name='skin_measurements')
    op.drop_index('idx_skin_measurements_measured_at', table_name='skin_measurements')
    op.drop_table('skin_measurements')
    op.drop_index('idx_usage_user_product', table_name='product_usage_history')
    op.drop_index('idx_usage_user_active', table_name='product_usage_history')
    op.drop_index('idx_usage_product', table_name='product_usage_history')
    op.drop_index('idx_usage_date_range', table_name='product_usage_history')
    op.drop_table('product_usage_history')
    op.drop_index('idx_effect_user_score', table_name='product_effect_analyses')
    op.drop_index('idx_effect_user_product', table_name='product_effect_analyses')
    op.drop_index('idx_effect_user_date', table_name='product_effect_analyses')
    op.drop_index('idx_effect_product', table_name='product_effect_analyses')
    op.drop_table('product_effect_analyses')
    op.drop_index('idx_users_skin_type', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_brand_name', table_name='products')
    op.drop_index('idx_products_active', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
